### ISSUE TITLE
Backup board and list board

### ISSUE THREAD

**Issue by bartounet16** [aliasaria/scrumblr#45]
Hello.
Is it possible to save board ??
After a stop/start of server i cannot see my old board...

For example i have created http://192.168.1.1/board

This bord is safe durin the server is up.

If the server is stop and start the board  http://192.168.1.1/board is empty !!!!

Secondary, how can i list all existing board.??

**Comment by I-Dont-Want-To-Create-An-Account** [comment]
I'm facing the same issue - is there some reason this issue was closed?

**Comment by aliasaria** [comment]
The issue is about your database (redis). If you want your database to persist between restarts, you need to ensure that redis is storing its data on disk, not just in memory. More information about this is here:

http://redis.io/topics/persistence

Basically, redis stores snapshots in an RDB file that you need to make sure is enabled (it should be by default) and that it gets reloaded on restart.

**Comment by I-Dont-Want-To-Create-An-Account** [comment]
Perfect. Thanks for the advice. I appreciate it    :-)
