### ISSUE TITLE
We need to use MySql Database.

### ISSUE THREAD

**Issue by makinux-git** [aliasaria/scrumblr#69]
Dear Ali,

I am working on your nice project!

We need to use MySql Database. Please advise me on the needed tables and columns. I already started guessing tables and columns. 

But there is something wrong I can't figure out. I think it would be a very nice addition to your awesome project if you add MySQL support.

I promice I will push the new version so you all the community including You can make benefit from the addition of MySQl.

Waiting your repoonse ASAP.

**Comment by notsosuperjamie** [comment]
Any luck with trying to get it to work on MySql?

**Comment by makinux-git** [comment]
Yes I did ! :)

**Comment by muji8u** [comment]
@makinux-git  do you think you could help me doing what u did?

**Comment by devaffair** [comment]
I think MongoDb (using mongo labs) would be the better choice.   Working on that my self

**Comment by neithere** [comment]
@devaffair any luck with MongoDB? I'm currently trying to understand why the bundled `lib/data/mongodb.js` does not work and it's very confusing.

**Comment by neithere** [comment]
@devaffair UPD: looks like the main problems were:

1. theme not being set (fixed by upsert in `setTheme()` + `callback(room.theme || DEFAULT_THEME)` in `get_theme()`)
2. `getAllCards()` being a hash of documents instead of a list (easy to fix)
3. `getBoardSize()` returning `undef` instead of a hash (actually I had to add some defaults to make sure it works — no idea why this wasn't needed for Redis backend).

**Comment by Bisonfan95** [comment]
@makinux-git can you share your code with MySQL support please?
