### ISSUE TITLE
Replace images with free artwork

### ISSUE THREAD

**Issue by Calinou** [aliasaria/scrumblr#71]
The current artwork (licensed under CC BY-NC-ND) can potentially turn the program proprietary.

I can perhaps work on this, with varying levels of success. Maybe we could switch to flat design too?

Resources:
- http://opengameart.org/
- https://openclipart.org/

**Comment by ocdtrekkie** [comment]
I would suggest if you're looking for flat design, you're probably looking for a different app or fork entirely, as @aliasaria very clearly said "the look is meant to be as close as possible to Well.ca's real sprint board ... you may find this annoying but we find it kinda funny" which indicates this is an intentional choice.

How does CC BY-NC-ND make the program proprietary? The Non-Commercial element might be problematic for some potential users, but does that render the work "proprietary"? No Derivatives likely only means modifications to the images themselves, which users will not need to modify.

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi
