### ISSUE TITLE
To be able to choose post-it color directly 

### ISSUE THREAD

**Issue by SergeFranceschino** [aliasaria/scrumblr#97]

**Comment by ovizii** [comment]
how do you chose it indirectly? 
Sounds like you have found a workaround?

**Comment by SergeFranceschino** [comment]
No sorry it's not a workaround, it is a request.

**Comment by ovizii** [comment]
ah, sorry, I understood you had found a way. well, then here's my +1 :-)

**Comment by nricheton** [comment]
+1 :-)

**Comment by ocdtrekkie** [comment]
@nricheton Please do not comment "+1" on GitHub. It doesn't provide any meaningful contribution. You can, however, use the "+ :)" icon on the top left to give an issue or comment a thumbs up.

**Comment by AlainBecker** [comment]
Just my 20¢ on UI : 

If this is to be done, for the sake of ease-of-use, instead of having to "configure" each new note _afterwards_, there could be **several piles of unused sticky notes**, one for each color, instead of a generic (+) button. 

For user feed-back, a (+) sign could appear when mousing over a pile.

The (+) button's function, which seem to be something like
`
    create_new_note() { 
      note = new Note(pick_some_random_color())
    }
`
would be moved to the new piles and become (functional _pseudo-code_ again)
`create_new_note(this_color) { note = new Note(this_color) }`

This could keep the UX straight-forward.

**Comment by lspevak** [comment]
Please, check also my fork with direct color selection and many other improvements: [lspevak/scrumblr](https://github.com/lspevak/scrumblr).

**Comment by aliasaria** [comment]
Fixed in 1e4d964e5bbe93b505cbb7601f2e7302b2173285
